import { createHash } from 'node:crypto';
import { ConflictException,ForbiddenException,Injectable,NotFoundException } from '@nestjs/common';
import { ReceivingDatabaseService } from './receiving-database.service.js';
export interface GoodsReceiptLineInput{poLineId:string;skuId:string;batchId:string;quantity:number;uomId:string;locationId:string;stockStatus:string;}
export interface CreateGoodsReceiptInput{grCode:string;poId:string;warehouseId:string;receivedDate?:string;externalReference?:string;lines:GoodsReceiptLineInput[];}
interface GrRow{id:string;gr_code:string;po_id:string;warehouse_id:string|null;status:string;received_date:string;received_by:string;idempotency_key:string;request_hash:string|null;version:number;post_idempotency_key:string|null;post_request_hash:string|null;}
interface GrLine{id:string;po_line_id:string;sku_id:string;batch_id:string;quantity:string;uom_id:string;location_id:string;stock_status:string;}
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function whole(value:number){if(!Number.isSafeInteger(value)||value<=0)throw new ConflictException('quantity must be a positive whole-case quantity');return value;}

@Injectable()
export class GoodsReceiptService{
  constructor(private readonly db:ReceivingDatabaseService){}
  async create(actorId:string,input:CreateGoodsReceiptInput,idempotencyKey:string,correlationId:string){
    if(input.receivedDate&&Number.isNaN(Date.parse(input.receivedDate)))throw new ConflictException('receivedDate must be a valid ISO date-time');
    const normalized={...input,grCode:input.grCode.trim().toUpperCase(),externalReference:input.externalReference?.trim()||null,
      receivedDate:input.receivedDate??null,lines:input.lines?.map((line)=>({...line,quantity:whole(line.quantity)}))??[]};
    if(!normalized.grCode||normalized.lines.length===0)throw new ConflictException('GR code and at least one line are required');const requestHash=hash(normalized);
    try{return await this.db.transaction(async(client)=>{
      const replay=await this.claimIdempotency(client,actorId,'CREATE_GOODS_RECEIPT',idempotencyKey,requestHash);
      if(replay)return{...(replay as Record<string,unknown>),replayed:true};
      if(!await this.db.hasAccess(actorId,'RECEIVING.CREATE',input.warehouseId,client))throw new ForbiddenException('RECEIVING.CREATE is required for the warehouse scope');
      const poResult=await client.query<{status:string;warehouse_id:string|null}>(`SELECT status,warehouse_id FROM purchasing.purchase_order WHERE id=$1`,[input.poId]);const po=poResult.rows[0];
      if(!po)throw new NotFoundException('Purchase order not found');if(po.warehouse_id!==input.warehouseId)throw new ConflictException('PO and receipt warehouse do not match');if(po.status!=='SENT'&&po.status!=='PARTIALLY_RECEIVED')throw new ConflictException(`Cannot receive goods for PO in ${po.status} status`);
      const inserted=await client.query<GrRow>(`INSERT INTO receiving.goods_receipt
        (gr_code,po_id,warehouse_id,status,received_date,received_by,idempotency_key,request_hash,external_reference,correlation_id)
        VALUES($1,$2,$3,'DRAFT',$4,$5,$6,$7,$8,$9) RETURNING *`,[normalized.grCode,input.poId,input.warehouseId,normalized.receivedDate??new Date().toISOString(),actorId,idempotencyKey,requestHash,normalized.externalReference,correlationId]);
      const receipt=inserted.rows[0];if(!receipt)throw new Error('Failed to create goods receipt');
      for(const line of normalized.lines){
        const ref=await client.query<{sku_id:string;uom_id:string;warehouse_id:string;manufacturing_date:string;expiration_date:string}>(`SELECT po_line.sku_id,po_line.uom_id,zone.warehouse_id,batch.manufacturing_date,batch.expiration_date
          FROM purchasing.purchase_order_line po_line JOIN inventory.batch batch ON batch.id=$3 AND batch.sku_id=po_line.sku_id
          JOIN warehouse.location location ON location.id=$4 JOIN warehouse.zone zone ON zone.id=location.zone_id
          WHERE po_line.id=$1 AND po_line.po_id=$2`,[line.poLineId,input.poId,line.batchId,line.locationId]);const valid=ref.rows[0];
        if(!valid)throw new ConflictException('PO line, batch or location does not match receipt');if(valid.sku_id!==line.skuId||valid.uom_id!==line.uomId)throw new ConflictException('Receipt SKU or UOM does not match PO line');
        if(valid.warehouse_id!==input.warehouseId)throw new ConflictException('Receipt location is outside the selected warehouse');if(new Date(valid.manufacturing_date)>=new Date(valid.expiration_date))throw new ConflictException('MFG_DATE must be before EXP_DATE');
        if((await client.query('SELECT 1 FROM inventory.stock_status WHERE code=$1',[line.stockStatus])).rowCount===0)throw new NotFoundException('Stock status not found');
        await client.query(`INSERT INTO receiving.goods_receipt_line(gr_id,po_line_id,sku_id,batch_id,quantity,uom_id,location_id,stock_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,
          [receipt.id,line.poLineId,line.skuId,line.batchId,line.quantity,line.uomId,line.locationId,line.stockStatus]);
      }
      const response=await this.load(client,receipt);await this.completeIdempotency(client,actorId,'CREATE_GOODS_RECEIPT',idempotencyKey,response,201);
      await this.audit(client,actorId,'CREATE',receipt,input.warehouseId,correlationId,undefined,{status:'DRAFT',lineCount:normalized.lines.length});return{...response,replayed:false};
    });}catch(error){if(error instanceof Error&&error.message.includes('unique constraint'))throw new ConflictException('Goods receipt code, reference or idempotency key already exists');throw error;}
  }
  async findOne(actorId:string,id:string){const rows=await this.db.query<GrRow>('SELECT * FROM receiving.goods_receipt WHERE id=$1',[id]);const receipt=rows[0];if(!receipt)throw new NotFoundException('Goods receipt not found');if(!receipt.warehouse_id||!await this.db.hasAccess(actorId,'RECEIVING.VIEW',receipt.warehouse_id))throw new ForbiddenException('RECEIVING.VIEW is required');return this.db.transaction((client)=>this.load(client,receipt));}
  async confirm(actorId:string,id:string,expectedVersion:number,correlationId:string){return this.db.transaction(async(client)=>{const receipt=await this.lock(client,id);
    if(!receipt.warehouse_id||!await this.db.hasAccess(actorId,'RECEIVING.CREATE',receipt.warehouse_id,client))throw new ForbiddenException('RECEIVING.CREATE is required');this.state(receipt,'DRAFT',expectedVersion);
    const updated=await client.query<GrRow>(`UPDATE receiving.goods_receipt SET status='RECEIVING',confirmed_by=$2,confirmed_at=now(),version=version+1,updated_at=now() WHERE id=$1 RETURNING *`,[id,actorId]);
    await this.audit(client,actorId,'CONFIRM',receipt,receipt.warehouse_id,correlationId,undefined,{status:'RECEIVING'});return this.load(client,updated.rows[0]!);});}
  async post(actorId:string,id:string,expectedVersion:number,idempotencyKey:string,correlationId:string,reason?:string){const requestHash=hash({id,expectedVersion,reason:reason?.trim()||null});return this.db.transaction(async(client)=>{
    const replay=await this.claimIdempotency(client,actorId,'POST_GOODS_RECEIPT',idempotencyKey,requestHash);if(replay)return{...(replay as Record<string,unknown>),replayed:true};
    const receipt=await this.lock(client,id);if(receipt.status==='POSTED'){if(receipt.post_idempotency_key===idempotencyKey&&receipt.post_request_hash===requestHash){const response=await this.postResponse(client,id);await this.completeIdempotency(client,actorId,'POST_GOODS_RECEIPT',idempotencyKey,response,200);return{...response,replayed:true};}throw new ConflictException('Goods receipt is already posted');}
    if(!receipt.warehouse_id||!await this.db.hasAccess(actorId,'RECEIVING.POST',receipt.warehouse_id,client))throw new ForbiddenException('RECEIVING.POST is required');this.state(receipt,'RECEIVING',expectedVersion);
    const lines=await client.query<GrLine>('SELECT * FROM receiving.goods_receipt_line WHERE gr_id=$1 ORDER BY id FOR UPDATE',[id]);if(lines.rowCount===0)throw new ConflictException('Cannot post an empty goods receipt');
    const poResult=await client.query<{status:string;receiving_tolerance_percent:string;supplier_id:string}>('SELECT status,receiving_tolerance_percent,supplier_id FROM purchasing.purchase_order WHERE id=$1 FOR UPDATE',[receipt.po_id]);const po=poResult.rows[0];if(!po||!['SENT','PARTIALLY_RECEIVED'].includes(po.status))throw new ConflictException('Purchase order is not open for receiving');
    const movementIds:string[]=[];
    for(const line of lines.rows){const quantity=Number(line.quantity);let stockStatus=line.stock_status;
      const batchResult=await client.query<{expiration_date:string}>('SELECT expiration_date FROM inventory.batch WHERE id=$1',[line.batch_id]);const batch=batchResult.rows[0];if(!batch)throw new NotFoundException('Batch not found');
      const remainingDays=Math.floor((new Date(batch.expiration_date).getTime()-new Date(receipt.received_date).getTime())/86_400_000);
      const policyResult=await client.query<{min_remaining_days:number;exception_mode:string}>(`SELECT min_remaining_days,exception_mode FROM receiving.mrsl_policy WHERE sku_id=$1 AND valid_from<=now() AND(valid_until IS NULL OR valid_until>now()) ORDER BY valid_from DESC LIMIT 1`,[line.sku_id]);const policy=policyResult.rows[0];
      if(policy&&remainingDays<policy.min_remaining_days){if(policy.exception_mode==='REJECT')throw new ConflictException(`MRSL_REJECTED:${line.sku_id}:${remainingDays}:${policy.min_remaining_days}`);if(policy.exception_mode==='QUARANTINE')stockStatus='QUARANTINED';if(policy.exception_mode==='ALLOW_WITH_APPROVAL')await this.consumeException(client,id,line.id,'MRSL',actorId);}
      const poLineResult=await client.query<{ordered_qty:string;received_qty:string}>(`SELECT ordered_qty,received_qty FROM purchasing.purchase_order_line WHERE id=$1 AND po_id=$2 FOR UPDATE`,[line.po_line_id,receipt.po_id]);const poLine=poLineResult.rows[0];if(!poLine)throw new ConflictException('Matching PO line not found');
      const ordered=Number(poLine.ordered_qty),received=Number(poLine.received_qty),newReceived=received+quantity,tolerance=Number(po.receiving_tolerance_percent);
      if(newReceived>ordered*(1+tolerance/100))await this.consumeException(client,id,line.id,'OVER_RECEIPT',actorId);
      if(newReceived>ordered*1.1)throw new ConflictException('ABSOLUTE_OVER_RECEIPT_LIMIT_EXCEEDED');
      const minResult=await client.query<{minimum_quantity:string}>(`SELECT minimum_quantity FROM catalog.wholesale_quantity_policy WHERE sku_id=$1 AND direction='INBOUND' AND(supplier_id IS NULL OR supplier_id=$2)
        AND valid_from<=now() AND(valid_until IS NULL OR valid_until>now()) ORDER BY(supplier_id IS NOT NULL)DESC,valid_from DESC LIMIT 1`,[line.sku_id,po.supplier_id]);const minimum=Number(minResult.rows[0]?.minimum_quantity??0);
      if(minimum>0&&quantity<minimum&&quantity!==Math.max(ordered-received,0))await this.consumeException(client,id,line.id,'MINIMUM_QUANTITY',actorId);
      await client.query('UPDATE purchasing.purchase_order_line SET received_qty=$2 WHERE id=$1',[line.po_line_id,newReceived]);await this.allocateSchedules(client,line.po_line_id,quantity);
      const movement=await client.query<{id:string}>(`SELECT inventory.post_movement('RECEIPT','GOODS_RECEIPT',$1,$2,$3,$4,$5,NULL,NULL,NULL,$6,$7,$8,$9,$10,$11) id`,
        [id,`${id}:${line.id}`,line.sku_id,line.batch_id,quantity,receipt.warehouse_id,line.location_id,stockStatus,actorId,correlationId,reason??null]);if(!movement.rows[0]?.id)throw new Error('Failed to post inventory movement');movementIds.push(movement.rows[0].id);
      await client.query(`UPDATE inventory.batch SET first_received_date=least(coalesce(first_received_date,$2::date),$2::date) WHERE id=$1`,[line.batch_id,receipt.received_date]);
    }
    const totals=await client.query<{complete:boolean;any_received:boolean}>(`SELECT bool_and(received_qty>=ordered_qty) complete,bool_or(received_qty>0) any_received FROM purchasing.purchase_order_line WHERE po_id=$1`,[receipt.po_id]);const poStatus=totals.rows[0]?.complete?'RECEIVED':'PARTIALLY_RECEIVED';
    await client.query('UPDATE purchasing.purchase_order SET status=$2,version=version+1,updated_at=now() WHERE id=$1',[receipt.po_id,poStatus]);
    const updated=await client.query<GrRow>(`UPDATE receiving.goods_receipt SET status='POSTED',post_idempotency_key=$2,post_request_hash=$3,posted_by=$4,posted_at=now(),version=version+1,updated_at=now() WHERE id=$1 RETURNING *`,[id,idempotencyKey,requestHash,actorId]);
    const response={documentId:id,status:'POSTED',purchaseOrderStatus:poStatus,movementIds};await this.completeIdempotency(client,actorId,'POST_GOODS_RECEIPT',idempotencyKey,response,200);
    await this.audit(client,actorId,'POST',updated.rows[0]!,receipt.warehouse_id,correlationId,reason,{status:'POSTED',movementIds});return{...response,replayed:false};
  });}
  private async consumeException(client:import('pg').PoolClient,receiptId:string,lineId:string,type:string,actorId:string){const exception=await client.query<{id:string}>(`SELECT id FROM receiving.receipt_exception_request WHERE goods_receipt_id=$1 AND goods_receipt_line_id=$2 AND exception_type=$3 AND status='APPROVED' ORDER BY approved_at LIMIT 1 FOR UPDATE`,[receiptId,lineId,type]);const id=exception.rows[0]?.id;if(!id)throw new ConflictException(`${type}_APPROVAL_REQUIRED`);await client.query(`UPDATE receiving.receipt_exception_request SET status='CONSUMED',consumed_by=$2,consumed_at=now(),version=version+1,updated_at=now() WHERE id=$1`,[id,actorId]);}
  private async allocateSchedules(client:import('pg').PoolClient,poLineId:string,quantity:number){let remaining=quantity;const schedules=await client.query<{id:string;promised_quantity:string;accepted_quantity:string}>(`SELECT id,promised_quantity,accepted_quantity FROM purchasing.purchase_order_delivery_schedule WHERE purchase_order_line_id=$1 AND status IN('OPEN','PARTIALLY_RECEIVED') ORDER BY promised_date,schedule_number FOR UPDATE`,[poLineId]);
    for(const schedule of schedules.rows){if(remaining<=0)break;const capacity=Number(schedule.promised_quantity)-Number(schedule.accepted_quantity);const accepted=Math.min(Math.max(capacity,0),remaining);if(accepted>0){const total=Number(schedule.accepted_quantity)+accepted;await client.query(`UPDATE purchasing.purchase_order_delivery_schedule SET accepted_quantity=$2,status=CASE WHEN $2>=promised_quantity THEN 'RECEIVED' ELSE 'PARTIALLY_RECEIVED' END,updated_at=now() WHERE id=$1`,[schedule.id,total]);remaining-=accepted;}}
    if(remaining>0&&schedules.rows.length>0){const last=schedules.rows.at(-1)!;await client.query(`UPDATE purchasing.purchase_order_delivery_schedule SET accepted_quantity=accepted_quantity+$2,status='RECEIVED',updated_at=now() WHERE id=$1`,[last.id,remaining]);}}
  private async claimIdempotency(client:import('pg').PoolClient,actor:string,operation:string,key:string,requestHash:string){await client.query(`INSERT INTO platform.idempotency_record(caller_id,operation,idempotency_key,request_hash,locked_until) VALUES($1,$2,$3,$4,now()+interval '5 minutes') ON CONFLICT DO NOTHING`,[actor,operation,key,requestHash]);const rows=await client.query<{request_hash:string;state:string;response_body:unknown}>(`SELECT request_hash,state,response_body FROM platform.idempotency_record WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3 FOR UPDATE`,[actor,operation,key]);const row=rows.rows[0];if(!row)throw new Error('Failed to claim idempotency key');if(row.request_hash!==requestHash)throw new ConflictException('IDEMPOTENCY_CONFLICT');if(row.state==='COMPLETED')return row.response_body;if(row.state==='PROCESSING'&&row.response_body)throw new ConflictException('IDEMPOTENCY_IN_PROGRESS');return null;}
  private completeIdempotency(client:import('pg').PoolClient,actor:string,operation:string,key:string,response:unknown,status:number){return client.query(`UPDATE platform.idempotency_record SET state='COMPLETED',response_status=$4,response_body=$5::jsonb,completed_at=now(),locked_until=NULL WHERE caller_id=$1 AND operation=$2 AND idempotency_key=$3`,[actor,operation,key,status,JSON.stringify(response)]);}
  private state(row:GrRow,status:string,version:number){if(row.status!==status)throw new ConflictException(`Goods receipt must be ${status}`);if(Number(row.version)!==version)throw new ConflictException('VERSION_CONFLICT');}
  private async lock(client:import('pg').PoolClient,id:string){const rows=await client.query<GrRow>('SELECT * FROM receiving.goods_receipt WHERE id=$1 FOR UPDATE',[id]);if(!rows.rows[0])throw new NotFoundException('Goods receipt not found');return rows.rows[0];}
  private async load(client:import('pg').PoolClient,row:GrRow){const lines=await client.query<GrLine>('SELECT * FROM receiving.goods_receipt_line WHERE gr_id=$1 ORDER BY id',[row.id]);return{id:row.id,grCode:row.gr_code,poId:row.po_id,warehouseId:row.warehouse_id,status:row.status,receivedDate:row.received_date,receivedBy:row.received_by,version:Number(row.version),lines:lines.rows.map((line)=>({id:line.id,poLineId:line.po_line_id,skuId:line.sku_id,batchId:line.batch_id,quantity:Number(line.quantity),uomId:line.uom_id,locationId:line.location_id,stockStatus:line.stock_status}))};}
  private async postResponse(client:import('pg').PoolClient,id:string){const movement=await client.query<{id:string}>(`SELECT id FROM inventory.inventory_movement_ledger WHERE document_type='GOODS_RECEIPT' AND document_id=$1 ORDER BY created_at,id`,[id]);return{documentId:id,status:'POSTED',movementIds:movement.rows.map((row)=>row.id)};}
  private audit(client:import('pg').PoolClient,actor:string,action:string,row:GrRow,warehouse:string,correlation:string,reason?:string,after?:unknown){return client.query(`INSERT INTO audit.audit_event(actor_id,action,resource_type,resource_id,warehouse_id,correlation_id,reason,before_data,after_data) VALUES($1,$2,'GOODS_RECEIPT',$3,$4,$5,$6,$7::jsonb,$8::jsonb)`,[actor,action,row.id,warehouse,correlation,reason??null,JSON.stringify({status:row.status,version:Number(row.version)}),JSON.stringify(after??{})]);}
}
