import { BadRequestException,Body,Controller,Get,Headers,Param,Post,Req } from '@nestjs/common';
import { ReceiptExceptionService,type ReceiptExceptionType } from './receipt-exception.service.js';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function id(value:string|undefined,name:string){if(!value||!uuid.test(value))throw new BadRequestException(`${name} must be UUID`);return value;}function key(value:string|undefined){if(!value||value.length<16||value.length>128)throw new BadRequestException('Idempotency-Key must contain 16 to 128 characters');return value;}function version(value:unknown){if(!Number.isSafeInteger(value)||Number(value)<=0)throw new BadRequestException('expectedVersion must be a positive integer');return Number(value);}
@Controller('receipt-exceptions')export class ReceiptExceptionController{constructor(private readonly service:ReceiptExceptionService){}
  @Post()create(@Headers('x-actor-id')actor:string|undefined,@Headers('idempotency-key')k:string|undefined,@Req()req:{correlationId?:string},@Body()body:{exceptionCode:string;goodsReceiptId:string;goodsReceiptLineId?:string;exceptionType:ReceiptExceptionType;reason:string;evidence?:unknown}){id(body.goodsReceiptId,'goodsReceiptId');if(body.goodsReceiptLineId)id(body.goodsReceiptLineId,'goodsReceiptLineId');return this.service.create(id(actor,'actorId'),body,key(k),id(req.correlationId,'correlationId'));}
  @Get(':id')find(@Headers('x-actor-id')actor:string|undefined,@Param('id')exceptionId:string){return this.service.findOne(id(actor,'actorId'),id(exceptionId,'receiptExceptionId'));}
  @Post(':id/approve')approve(@Headers('x-actor-id')actor:string|undefined,@Param('id')exceptionId:string,@Req()req:{correlationId?:string},@Body()body:{expectedVersion?:number;reason?:string}){return this.service.decide(id(actor,'actorId'),id(exceptionId,'receiptExceptionId'),version(body.expectedVersion),'APPROVED',body.reason??'',id(req.correlationId,'correlationId'));}
  @Post(':id/reject')reject(@Headers('x-actor-id')actor:string|undefined,@Param('id')exceptionId:string,@Req()req:{correlationId?:string},@Body()body:{expectedVersion?:number;reason?:string}){return this.service.decide(id(actor,'actorId'),id(exceptionId,'receiptExceptionId'),version(body.expectedVersion),'REJECTED',body.reason??'',id(req.correlationId,'correlationId'));}
}
